### ISSUE TITLE
Server doesn't start after adding organization

### ISSUE THREAD

**Issue by Pauzie** [pritunl/pritunl#230] opened 2016-01-24 19:11 UTC
If we have five organization in server everything is fine. If we add the sixth the server doesn't start.
The error message: 

[XXX] Sun Jan 24 20:07:42 2016 ERROR Management socket exception
[XXX] Sun Jan 24 20:07:42 2016 OpenVPN 2.3.2 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on Dec  1 2014
[XXX] Sun Jan 24 20:07:42 2016 Cannot load CA certificate file [[INLINE]]: error:0906D066:PEM routines:PEM_read_bio:bad end line
[XXXX] Sun Jan 24 20:07:42 2016 Exiting due to fatal error

Thanks for help.

**Comment by zachhuff386** [comment] 2016-01-24 22:31
I'm not able to reproduce this. Check the logs in the web console or run the command `pritunl logs`

**Comment by zachhuff386** [comment] 2016-01-30 07:06
Duplicate of #236

**Closed by zachhuff386** 2016-01-30 07:06 UTC
Labels: duplicate
