### ISSUE TITLE
Server stopped unexpectedly

### ISSUE THREAD

**Issue by MrK42** [pritunl/pritunl#128] opened 2015-07-10 07:04 UTC
Hi i have some problems when i run pritunl on a ubuntu v-server. At one time on the day the server suddenly restarts or is not reachable anymore. In the web interface on Recent log entries "Server stopped unexpectedly" appears. And in the log files have followed entry:
##########################
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/dist-packages/pritunl/auth/app.py", line 13, in _wrapped
    return call(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pritunl/handlers/server.py", line 742, in server_operation_put
    svr.start()
  File "/usr/lib/python2.7/dist-packages/pritunl/server/server.py", line 794, in start 'server_id': self.id,
#######################
I also saw that one tun device was not shown at ifconfig on the time the server not working correctly.
I hope some have an idea what the problem is....

Regards
MrK

**Comment by zachhuff386** [comment] 2015-07-10 07:09
The error above is a timeout error, the error that caused it will be in the vpn server log or in the pritunl logs. It is most likely related to vserver, creating the tun interfaces requires escalated privileges to the host system.

**Closed by zachhuff386** 2015-07-10 07:09 UTC
Labels: question

**Comment by MrK42** [comment] 2015-07-10 07:33
hi thanks for your fast answer. I looked in the logs a little bit more an the error that occurs most is:

[winter-waterfall-6122][2015-06-26 16:02:47,546][ERROR] Server management socket path not found
  instance_id = ObjectId('558ce1def6b76201644563fb')
  socket_path = '/var/run/pritunl_558ce1def6b76201644563fb.sock'
  server_id   = ObjectId('555c7461f6b762016fc8a54f')
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 465, in _socket_thread
    self.connect()
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 510, in connect
    self.wait_for_socket()
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 409, in wait_for_socket
    socket_path=self.socket_path,
  File "/usr/lib/python2.7/dist-packages/pritunl/logger/__init__.py", line 59, in error
    kwargs['traceback'] = traceback.format_stack()
and i also found this error:

[winter-waterfall-6122][2015-07-10 01:39:01,250][ERROR] Exception on /status [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/dist-packages/pritunl/auth/app.py", line 13, in _wrapped
    return call(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pritunl/handlers/status.py", line 105, in status_get
    local_networks = utils.get_local_networks()
  File "/usr/lib/python2.7/dist-packages/pritunl/utils/network.py", line 84, in get_local_networks
    output = check_output_logged(['ifconfig'])
  File "/usr/lib/python2.7/dist-packages/pritunl/utils/misc.py", line 158, in check_output_logged
    return_code, cmd, output=stdoutdata)
CalledProcessError: Command '['ifconfig']' returned non-zero exit status 1
[winter-waterfall-6122][2015-07-10 01:39:01,257][ERROR] Popen returned error exit code
  cmd         = ['ifconfig']
  return_code = 1
Process stdout:
  lo        Link encap:Local Loopback
            inet addr:127.0.0.1  Mask:255.0.0.0
            inet6 addr: ::1/128 Scope:Host
            UP LOOPBACK RUNNING  MTU:65536  Metric:1
            RX packets:67304 errors:0 dropped:0 overruns:0 frame:0
            TX packets:67304 errors:0 dropped:0 overruns:0 carrier:0
            collisions:0 txqueuelen:0
            RX bytes:12568377 (12.5 MB)  TX bytes:12568377 (12.5 MB)

Process stderr:
tun17: error fetching interface information: Device not found
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/dist-packages/pritunl/wsgiserver/wsgiserver2.py", line 1531, in run
    conn.communicate()
  File "/usr/lib/python2.7/dist-packages/pritunl/wsgiserver/wsgiserver2.py", line 1359, in communicate
    req.respond()
  File "/usr/lib/python2.7/dist-packages/pritunl/wsgiserver/wsgiserver2.py", line 870, in respond
    self.server.gateway(self).respond()
  File "/usr/lib/python2.7/dist-packages/pritunl/wsgiserver/wsgiserver2.py", line 2284, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/dist-packages/pritunl/auth/app.py", line 13, in _wrapped
    return call(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pritunl/handlers/status.py", line 105, in status_get
    local_networks = utils.get_local_networks()
  File "/usr/lib/python2.7/dist-packages/pritunl/utils/network.py", line 84, in get_local_networks
    output = check_output_logged(['ifconfig'])
  File "/usr/lib/python2.7/dist-packages/pritunl/utils/misc.py", line 154, in check_output_logged
    stderr=stderrdata,
  File "/usr/lib/python2.7/dist-packages/pritunl/logger/__init__.py", line 59, in error
    kwargs['traceback'] = traceback.format_stack()
[winter-waterfall-6122][2015-07-10 08:34:14,706][ERROR] Exception on /server/555c6cd5f6b762016fc89f
61/start [PUT]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/dist-packages/pritunl/auth/app.py", line 13, in _wrapped
    return call(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pritunl/handlers/server.py", line 742, in server_operation_put
    svr.start()
  File "/usr/lib/python2.7/dist-packages/pritunl/server/server.py", line 794, in start
    'server_id': self.id,
ServerStartError: Server start timed out. {'server_id': ObjectId('555c6cd5f6b762016fc89f61')}
[winter-waterfall-6122][2015-07-10 08:34:14,706][ERROR] Exception on /server/555c6cd5f6b762016fc89f
61/start [PUT]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/dist-packages/pritunl/auth/app.py", line 13, in _wrapped
    return call(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pritunl/handlers/server.py", line 742, in server_operation_put
    svr.start()
  File "/usr/lib/python2.7/dist-packages/pritunl/server/server.py", line 794, in start
    'server_id': self.id,
ServerStartError: Server start timed out. {'server_id': ObjectId('555c6cd5f6b762016fc89f61')}


sorry i dont want to annoy you, but i dont know what i can do to fix this issue

Regards
MrK

**Comment by zachhuff386** [comment] 2015-07-10 07:39
It most likely won't run on a vserver. The issue is related to the vserver that isn't able to create the virtual interface.

**Comment by zachhuff386** [comment] 2015-09-08 16:26
Moving all information for error "Server stopped unexpectedly" to #158
